[package]
name = "agdk-mainloop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
android_logger = "0.11.0"
game-activity = { path="../../game-activity" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name="main"
crate_type=["cdylib"]