[package]
name = "agdk-mainloop"
version = "0.1.0"
edition = "2021"

[dependencies]
android-activity = { version = "0.5.0", features = ["native-activity"] }
android_logger = "0.11.0"
log = "0.4"
ndk = "0.8.0"

[lib]
name = "main"
crate_type = ["cdylib"]
