[package]
name = "agdk-cpal"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
android_logger = "0.13"
android-activity = { version = "0.5", features = ["game-activity"] }
cpal = "0.15"
atomic_float = "0.1"
anyhow = "1"

[lib]
name="main"
crate_type=["cdylib"]
