name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-C debuginfo=0 --deny warnings"
  RUSTDOCFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable]
    steps:
      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust_version }}

      - name: Install Rust targets
        run: >
          rustup target add
          aarch64-linux-android
          armv7-linux-androideabi
          x86_64-linux-android
          i686-linux-android

      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup shared Cargo target
        # Each example is in a separate workspace but we want to use
        # a shared target to speed up builds of all examples
        run: mkdir shared-target

      - name: Build agdk-mainloop example
        working-directory: agdk-mainloop
        run: >
          CARGO_TARGET_DIR=$GITHUB_WORKSPACE/shared-target cargo ndk
          -t arm64-v8a
          -t armeabi-v7a
          -t x86_64
          -t x86
          -o app/src/main/jniLibs/ -- build

      - name: Build na-mainloop example
        working-directory: na-mainloop
        run: >
          CARGO_TARGET_DIR=$GITHUB_WORKSPACE/shared-target cargo ndk
          -t arm64-v8a
          -t armeabi-v7a
          -t x86_64
          -t x86
          -o app/src/main/jniLibs/ -- build

      - name: Build agdk-egui example
        working-directory: agdk-egui
        run: >
          CARGO_TARGET_DIR=$GITHUB_WORKSPACE/shared-target cargo ndk
          -t arm64-v8a
          -t armeabi-v7a
          -t x86_64
          -t x86
          -o app/src/main/jniLibs/ -- build

      - name: Build agdk-eframe example
        working-directory: agdk-eframe
        run: >
          CARGO_TARGET_DIR=$GITHUB_WORKSPACE/shared-target cargo ndk
          -t arm64-v8a
          -t armeabi-v7a
          -t x86_64
          -t x86
          -o app/src/main/jniLibs/ -- build

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Format
        run: |
          for dir in agdk-* na-*; do
            cd $GITHUB_WORKSPACE/$dir
            cargo fmt --all -- --check
          done
